/**:
  ros__parameters:
    use_sim_time: True

    controller_server:
      ros__parameters:
        controller_plugins: ["FollowPath"]
        FollowPath:
          plugin: "nav2_constrained_smoother::ConstrainedSmoother"
